### ISSUE TITLE
Track & clip colors

### ISSUE THREAD

**Issue by jminor** [OpenTimelineIO/raven#11]
It would be great to have the ability to color code clips and/or tracks in Raven.

For starters, colors could be set in OTIO metadata, but once that is working, we could explore adding that as an official schema feature in OTIO.

**Comment by darbyjohnston** [comment]
Are you thinking about a pre-defined palette or arbitrary RGB colors?

**Comment by jminor** [comment]
Marker colors come from a pre-defined set, which is convenient when quickly picking something, but rather of awkward when interchanging with other systems where the colors are different. I guess clip colors would be similar?

I mocked this up to try it out...
<img width="1393" alt="image" src="https://github.com/OpenTimelineIO/raven/assets/169599/51e2f823-eeba-41ab-8633-8b80f5dd7c9d">

**Comment by jminor** [comment]
Addressed by #14

**Comment by darbyjohnston** [comment]
Cool screenshot! Palettes are convenient but considering the clip/track colors are prominent in the UI (like your screenshot) it would be nice to have more control over the colors. Maybe RGB floats, like an Imath::Vec3?
