### ISSUE TITLE
Audio waveforms

### ISSUE THREAD

**Issue by jminor** [OpenTimelineIO/raven#15]
Most NLEs show audio waveform shapes in audio clips on the timeline. Raven would be greatly improved if it had this feature also.

Here's a mockup of what that could look like
<img width="1404" alt="image" src="https://github.com/OpenTimelineIO/raven/assets/169599/929b2d0e-25c2-4d4b-9705-afb14e9e0e09">

Adding such a feature, however, opens many questions about media file formats, loading of media reference target_urls, and other specifics which might be problematic. By design Raven doesn't show video, or play video or audio, so showing waveforms invites the question if the tool should go in that direction or not, which is... complicated.

**Comment by darbyjohnston** [comment]
tlRender will have support for audio waveforms soon, maybe that could help? :)

Other complications include handling multiple audio channels, bit rates, and sampling. Also handling audio files in .otioz files is another level of complexity.

**Comment by meshula** [comment]
A friend and I wrote this some years ago.

https://github.com/ddiakopoulos/libnyquist

It's very robust, and is used for desktop based webaudio, and also in a bunch of headsets; so it's known to be bug free and robust. It loads pretty much everything, and solves all of the vexing build issues certain audio format libraries present.

We use libsamplerate for high quality and performant resampling, and miniaudio for easy crossplatform integration. miniaudio works on ... everything.

[submodule "third_party/libnyquist"]
	path = third_party/libnyquist
	url = https://github.com/ddiakopoulos/libnyquist.git
[submodule "third_party/libsamplerate"]
	path = third_party/libsamplerate
	url = https://github.com/libsndfile/libsamplerate.git
[submodule "third_party/miniaudio"]
	path = third_party/miniaudio
	url = https://github.com/mackron/miniaudio.git

**Comment by darbyjohnston** [comment]
That looks quite nice, I’m currently using the FFmpeg swresample library which works well but is a heavy dependency.

**Comment by jminor** [comment]
Once this feature lands in tlRender, maybe we can look into synchronizing the playhead between tlRender and Raven instead of having redundant features in both...

**Comment by jminor** [comment]
Thinking about this more, I feel that we should avoid reading media in Raven, and rely on other tools for features like this, video, etc.
