### ISSUE TITLE
Attempt to build on MacOS Ventura 13.4 M1 Max

### ISSUE THREAD

**Issue by adamhawkey** [OpenTimelineIO/raven#16]
In an attempt to build raven on MacOS Ventura 13.4 on M1 Max, I see the following errors"

`
build % cmake ..
-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done

CMake Error at CMakeLists.txt:54 (add_subdirectory):
  The source directory

    /usr/local/bin/raven-main/libs/opentimelineio

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:66 (add_subdirectory):
  The source directory

    /usr/local/bin/raven-main/libs/glfw

  does not contain a CMakeLists.txt file.
`

I figured I'd ask here first, thanks.

**Comment by JeanChristopheMorinPerso** [comment]
Try to run `git submodule update --init --recursive` in the root of the repo.

**Comment by jminor** [comment]
Probably your git submodules didn't get checked out. Try this:
```
git submodule init
git submodule update
```
and then build again.

**Comment by jminor** [comment]
Haha. @JeanChristopheMorinPerso beat me to it :)

**Comment by adamhawkey** [comment]
Thank you both.  Problem seemed to stem from downloading a .zip instead of cloning.
Built and running fine now.
