### ISSUE TITLE
Clip color obscures important text details

### ISSUE THREAD

**Issue by jminor** [OpenTimelineIO/raven#20]
Bug:
When a clip is selected, it is highlighted in white, which is the same color as some of the text on the clip, making the text unreadable. Furthermore, when adjusting a clip's color in the inspector, the clip color is not visible until you deselect the clip.

Suggested Fix:
- The timecode text on each clip could flip from white to black depending on the clip's fill color (like the clip name text does already).
- A better choice for the selection highlight color (perhaps a tint, brighten or darken) instead of pure white could work better.
- Both of these problems would be avoided if the selection highlight was a border instead of coloring the entire clip.

**Comment by jminor** [comment]
FYI, this was partially addressed by #22 but could still use some improvement.

**Comment by yaash45** [comment]
I'd love to take this issue on as part of ASWF Dev Days 2024!
