### ISSUE TITLE
Rocky Linux 8.10 -  Cmake - install

### ISSUE THREAD

**Issue by chlowden** [OpenTimelineIO/raven#84]
Hello
Has anyone managed install raven on Rocky Linux 8 ?
I am getting a cmake error
`(base) [admin@LOWROCKY build]$   cmake ..
-- Checking for module 'gtk+-3.0'
--   Found gtk+-3.0, version 3.22.30
-- Found OpenGL: /usr/lib64/libOpenGL.so   
CMake Error at CMakeLists.txt:54 (add_subdirectory):
  The source directory

    /home/admin/Downloads/raven-main/libs/opentimelineio

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:66 (add_subdirectory):
  The source directory

    /home/admin/Downloads/raven-main/libs/glfw

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
`
Thank you

**Comment by jminor** [comment]
Please run this:
```
% git submodule init
% git submodule update
``
and then try again.

**Comment by jminor** [comment]
@chlowden did that help at all?

**Comment by chlowden** [comment]
Hello, Sorry for my delay in replying ... 
`(base) [admin@LOWROCKY raven-main]$ git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /home/admin/Downloads/raven-main/.git/
(base) [admin@LOWROCKY raven-main]$ git submodule init
(base) [admin@LOWROCKY raven-main]$ git submodule update
(base) [admin@LOWROCKY raven-main]$ git submodule update --init --recursive
(base) [admin@LOWROCKY raven-main]$ mkdir build
mkdir: cannot create directory ‘build’: File exists
(base) [admin@LOWROCKY raven-main]$ cd build
(base) [admin@LOWROCKY build]$ cmake ..
CMake Error at CMakeLists.txt:54 (add_subdirectory):
  The source directory

    /home/admin/Downloads/raven-main/libs/opentimelineio

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:66 (add_subdirectory):
  The source directory

    /home/admin/Downloads/raven-main/libs/glfw

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!`


![image](https://github.com/user-attachments/assets/b147fe22-9c5f-48ae-b7fa-355b7107d4cc)
Sadly ... I'm missing something

**Comment by jminor** [comment]
In the log above, you ran `git init` which seems to have overwritten the `.git` folder, or maybe it wasn't there to begin with? That might be the clue we needed. Perhaps you downloaded a ZIP instead of using git clone? That would also explain the problem since the ZIP download does not include submodules.

Please delete whatever you downloaded and start over like this:

```
  git clone --recursive git@github.com:OpenTimelineIO/raven.git
  mkdir build
  cd build
  cmake ..
  cmake --build . -j
  ./raven ../example.otio
```

**Comment by chlowden** [comment]
![image](https://github.com/user-attachments/assets/30fcf437-7885-49dd-9f4f-370d5aa59f25)

I've got it working. Thank you for your suggestion. Below is the method that worked for me ..

`
cd /Downloads
sudo git clone --recursive https://github.com/OpenTimelineIO/raven.git
cd raven
sudo mkdir build
cd build
sudo cmake ..
sudo cmake --build . -j ./raven ../example.otio
`
There is a strange issue of having 2 windows, one is grey and the other is the GUI. If I try to resize either, the app may crash or I have to close the app to get the GUI back in front of the grey box.
